# This file was generated by GoReleaser. DO NOT EDIT.
cask "imgcompress" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1668aaf8319a3591a144562b6ea22b2d6d46441bf481f9c21fbb8d08d286e9e4"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a47e55ae7322ff5f982fe56fe845422cd0d71d1359f1694179f1b056052924d3"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c60a148ac27790c3ebace2e4881d159f772d96b1b52238f45d1bca65e6977270"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c99668985fd03e41e529336ec6abfb28826de1db655e9a512bc79e271c7cc31"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_linux_arm64.tar.gz"
    end
  end

  name "imgcompress"
  desc "Compress images locally to fit upload size limits"
  homepage "https://github.com/dsemischastnov/imgcompress"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imgcompress"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imgcompress"]
    end
  end

  # No zap stanza required

end
