# This file was generated by GoReleaser. DO NOT EDIT.
cask "imgcompress" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9b78d06642df60d0bc4483df3000c82a5ae8845dcc8809a866c833fa445f2dad"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b042fed7f8a322b810f65076d402f4c6c481f703f2427a0e87d9db7a197ef998"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f82ddf041960b34f5ca778ca8c9cc4d33109e144941aa2302cbcbda12c23897"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f20c429680e85dfbf2a4c41fec8492babed755db5b51610f3254d032953d68d"
      url "https://github.com/dsemischastnov/imgcompress/releases/download/v#{version}/imgcompress_#{version}_linux_arm64.tar.gz"
    end
  end

  name "imgcompress"
  desc "Compress images locally to fit upload size limits"
  homepage "https://github.com/dsemischastnov/imgcompress"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imgcompress"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imgcompress"]
    end
  end

  # No zap stanza required

end
